const { AppError } = require('../controllers/error.controllers.js')
const userRouter = require('./users.routes.js')
const organizationsRouter = require('./organizations.routes.js')
const fundCategoriesRouter = require('./fund-categories.routes.js')
const campaignsRouter = require('./campaigns.routes.js')

const volunteersRouter = require('./volunteers.routes.js')
const paymentsRouter = require('./payments.routes.js')
const donationsRouter = require('./donations.routes.js')
const notificationRouter = require('./notifications.routes.js')
const walletRouter = require('./wallets.routes.js')
const commentsRouter = require('./comments.routes.js')
const reasonsRouter = require('./reasons.routes.js')
const reportRouter = require('./reports.routes.js')
const withdrawalRouter = require('./withdrawals.routes.js')
const transactionRouter = require('./transactions.routes.js')
const statisticsRouter = require('./statistics.routes.js')
const friendRouter = require('./friends.routes.js')
const HTTP_STATUS = require('../constants/httpStatus.js')

const route = (app) => {
  app.use('/v1/users', userRouter)
  app.use('/v1/organizations', organizationsRouter)
  app.use('/v1/campaigns', campaignsRouter)
  app.use('/v1/fund-categories', fundCategoriesRouter)
  app.use('/v1/volunteers', volunteersRouter)
  app.use('/v1/payments', paymentsRouter)
  app.use('/v1/donations', donationsRouter)
  app.use('/v1/notifications', notificationRouter)
  app.use('/v1/wallets', walletRouter)
  app.use('/v1/comments', commentsRouter)
  app.use('/v1/reasons', reasonsRouter)
  app.use('/v1/reports', reportRouter)
  app.use('/v1/withdrawals', withdrawalRouter)
  app.use('/v1/transactions', transactionRouter)
  app.use('/v1/statistics', statisticsRouter)
  app.use('/v1/friends', friendRouter)
  app.all(/(.*)/, (req, res, next) => {
    next(new AppError(`Can't find ${req.originalUrl} on this server!`, HTTP_STATUS.NOT_FOUND))
  })
}

module.exports = route
