const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH: 'Name must be between 1 and 100 characters',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  FIRST_NAME_IS_REQUIRED: 'First name is required',
  FIRST_NAME_LENGTH: 'First name must be between 2 and 30 characters',
  LAST_NAME_IS_REQUIRED: 'Last name is required',
  LAST_NAME_LENGTH: 'Last name must be between 2 and 30 characters',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_STRONG:
    'Password must be contain at least one uppercase letter, one lowercase letter, one number, and one special character',
  PASSWORD_LENGTH: 'Password must be between 8 and 50 characters',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_MATCH: 'Confirm password must match the password',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_IS8601_INVALID: 'Date of birth must be a valid ISO 8601 date',
  LOGIN_INCORRECT: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Login successfully',
  REGISTER_SUCCESS: 'Register successfully',
  UN_AUTHORIZATION: 'Unauthorized',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  LOGOUT_SUCCESS: 'Logout successfully',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_VERIFY_SUCCESS: 'Email verify successfully',
  EMAIL_VERIFY_FAILED: 'Email verify failed',
  EMAIL_WAS_VERIFIED: 'Email was verified',
  USER_NOT_FOUND: 'User not found',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend verify email successfully',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCCESS: 'Verify forgot password token successfully',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
  BIO_IS_STRING: 'Bio must be a string',
  BIO_LENGTH: 'Bio must be between 1 and 200 characters',
  LOCATION_IS_STRING: 'Location must be a string',
  LOCATION_LENGTH: 'Location must be between 1 and 200 characters',
  WEBSITE_IS_STRING: 'Website must be a string',
  WEBSITE_LENGTH: 'Website must be between 1 and 200 characters',
  USERNAME_IS_STRING: 'Username must be a string',
  USERNAME_INVALID: 'Username must be 1 to 15 characters long and only contain letters, numbers, or underscores',
  USERNAME_EXISTS: 'Username already exists',
  AVATAR_IS_STRING: 'Avatar must be a string',
  IMAGE_URL_IS_STRING: 'Image URL must be a string',
  IMAGE_URL_LENGTH: 'Image URL must be between 1 and 400 characters',
  UPDATE_PROFILE_SUCCESS: 'Update profile successfully',
  FOLLOWER_USER_ID_IS_NOT_EMPTY: 'Follower user ID is not empty',
  FOLLOW_SUCCESS: 'Follow successfully',
  CANNOT_FOLLOW_YOURSELF: 'Cannot follow yourself',
  ALREADY_FOLLOWING: 'Already following',
  UN_FOLLOW_SUCCESS: 'Unfollow successfully',
  HAVE_NOT_FOLLOWING: 'have not following user',
  CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
  NEW_PASSWORD_IS_SAME_OLD_PASSWORD: 'New password must be different from the old password.',
  OLD_PASSWORD_IS_REQUIRED: 'Old password is required',
  OLD_PASSWORD_IS_WRONG: 'Old password is wrong',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successfully',
  FORBIDDEN: 'Forbidden',
  USER_ID_REQUIRED: 'User ID is required',
  USER_ID_INVALID: 'User ID is invalid',
  REFRESH_TOKEN_IS_STRING: 'Refresh token must be a string',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  AVATAR_IS_REQUIRED: 'Avatar is required',
  TOKEN_INVALID: 'Token is invalid',
  ROLE_INVALID: 'Role is invalid',
  SORT_BY_INVALID: 'Sort by is include firstName, lastName, email, createdAt, updatedAt',
}

const COMMON = {
  PAGE_INVALID: 'Page must be a positive integer',
  PAGE_SIZE_INVALID: 'Page size must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer',
  LIMIT_MAX: 'Limit must not exceed 100',
  SORT_BY_INVALID: 'Sort by must be a valid field',
  SORT_ORDER_INVALID: 'Sort order must be either "asc" or "desc"',
  MEDIA_IS_ARRAY: 'Restaurant media must be an array',
  MEDIA_ITEM_INVALID: 'Each media item must be a valid object with type and url',
  MEDIA_ITEM_TYPE_INVALID: 'Media type must be one of the following: image, video, audio',
  MEDIA_ITEM_URL_INVALID: 'Media URL must be a valid URL',
  MEDIA_ITEM_URL_LENGTH: 'Media URL must be between 1 and 400 characters',
  MEDIA_ITEM_REQUIRED: 'At least one media item is required',
  MEDIA_ITEM_MAX: 'A maximum of 10 media items is allowed',
  MEDIA_ITEM_MIN: 'At least one media item is required',
  SEARCH_MUST_BE_STRING: 'Search must be a string',
  ID_IS_INVALID: 'ID is invalid',
  ID_IS_REQUIRED: 'ID is required',
  IS_ACTIVE_MUST_BE_BOOLEAN: 'isActive must be a boolean',
  ROLE_INVALID: 'Role is invalid'
}
const FUND_CATEGORY_MESSAGES = {
  CATEGORY_NAME_REQUIRED: 'Category name is required',
  CATEGORY_NAME_MUST_BE_STRING: 'Category name must be a string',
  CATEGORY_NAME_NOT_EMPTY: 'Category name must not be empty',
  CATEGORY_NAME_LENGTH_INVALID: 'Category name must be between 3 and 50 characters',
  CATEGORY_NAME_IS_EXIST: 'Category name already exists'
}

const ROLE_MESSAGES = {
  NAME_IS_REQUIRED: 'Role name is required',
  NAME_IS_INVALID: 'Role name must be a string',
  ROLE_IS_DUPLICATE: 'Role already exists',
  ROLE_ID_IS_REQUIRED: 'Role ID is required',
  ROLE_ID_IS_INVALID: 'Role ID is invalid'
}

const FUND_MESSAGES = {
  FUND_NAME_REQUIRED: 'Fund name is required',
  METHOD_ID_REQUIRED: 'Fundraising methods is required',
  METHOD_ID_INVALID: 'Fundraising methods ID must be a positive integer',
  FUND_NAME_MUST_BE_STRING: 'Fund name must be a string',
  FUND_NAME_NOT_EMPTY: 'Fund name must not be empty',
  FUND_NAME_LENGTH_INVALID: 'Fund name must be between 3 and 100 characters',
  AMOUNT_REQUIRED: 'Amount is required',
  AMOUNT_MUST_BE_NUMBER: 'Amount must be a number',
  AMOUNT_MINIMUM: 'Amount must be at least 0',
  CATEGORY_ID_REQUIRED: 'Category ID is required',
  CATEGORY_ID_MUST_BE_INTEGER: 'Category ID must be an integer',
  START_DATE_INVALID: 'Start date must be a valid date',
  END_DATE_INVALID: 'End date must be a valid date',
  BANNER_URL_REQUIRED: 'Banner is required',
  BANNER_URL_INVALID: 'Banner URL must be a valid URL',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_REQUIRED: 'Description is required',
  BANK_ACCOUNT_NUMBER_MUST_BE_STRING: 'Bank account number must be a string',
  BANK_ACCOUNT_NUMBER_IS_REQUIRED: 'Bank account number is required',
  BANK_NAME_MUST_BE_STRING: 'Bank name must be a string',
  BANK_NAME_REQUIRED: 'Bank name is required',
  BANK_BRANCH_MUST_BE_STRING: 'Bank branch must be a string',
  BANK_BRANCH_REQUIRED: 'Bank branch is required',
  PURPOSE_MUST_BE_STRING: 'Purpose must be a string',
  PURPOSE_REQUIRED: 'Purpose is required',
  URL_QR_CODE_INVALID: 'QR Code URL must be a valid URL',
  END_DATE_BEFORE_START_DATE: 'End date must be after start date',
  MILESTONE_REQUIRED: 'Milestones are required for Milestone fundraising method',
  MILESTONE_IS_ARRAY: 'Milestones must be an array',
  MILESTONE_INVALID: 'Milestones must be an array of objects with name, amount, and dueDate',
  MILESTONE_NAME_REQUIRED: 'Milestone name is required',
  MILESTONE_AMOUNT_REQUIRED: 'Milestone amount is required',
  MILESTONE_AMOUNT_MUST_BE_NUMBER: 'Milestone amount must be a number',
  MILESTONE_AMOUNT_MINIMUM: 'Milestone amount must be at least 0',
  MILESTONE_DUE_DATE_INVALID: 'Milestone due date must be a valid date',
  MILESTONE_ITEM_INVALID:
    'Each milestone must be a valid object with title,desc,targetAmount, achievedAmount, startDate, endDate, orderIndex',
  MEDIA_FUND_INVALID: 'Media fund must be an array',
  MEDIA_FUND_ITEM_INVALID: 'Each media fund item must be a valid object with type and url',
  MEDIA_FUND_ITEM_TYPE_INVALID: 'Media fund type must be one of the following: image, video',
  MEDIA_FUND_ITEM_URL_INVALID: 'Media fund URL must be a valid URL',
  MEDIA_FUND_ITEM_REQUIRED: 'At least one media fund item is required',
  MEDIA_FUND_ITEM_MAX: 'A maximum of 10 media fund items is allowed',
  MEDIA_FUND_ITEM_MIN: 'At least one media fund item is required',
  CREATOR_ID_IS_REQUIRED: 'Creator ID is required',
  CREATOR_ID_IS_INVALID: 'Creator ID must be a positive integer',
  SORT_BY_INVALID:
    'Sort by must be one of the following: startDate, endDate, targetAmount, currentAmount, status, createdAt',
  SORT_ORDER_INVALID: 'Sort order must be either "asc" or "desc"',
  STATUS_INVALID: 'Status must be one of the following: pending, active, completed, cancelled',
  CATEGORY_ID_MUST_BE_INTEGER: 'Category ID must be an integer',
  FUND_ID_REQUIRED: 'Fund ID is required',
  FUND_ID_INVALID: 'Fund ID must be a positive integer',
  NOT_FOUND: 'Fund not found',
  MILESTONE_NOT_ALLOWED: 'Milestones are not allowed for Time-Based fundraising method'
}

const CAMPAIGN_MESSAGES = {
  CAMPAIGN_ID_REQUIRED: 'Campaign ID is required',
  CAMPAIGN_ID_INVALID: 'Campaign ID must be a positive integer',
  CAMPAIGN_NAME_REQUIRED: 'Campaign name is required',
  CAMPAIGN_NAME_MUST_BE_STRING: 'Campaign name must be a string',
  CAMPAIGN_NAME_NOT_EMPTY: 'Campaign name must not be empty',
  CAMPAIGN_NAME_LENGTH_INVALID: 'Campaign name must be between 3 and 100 characters',
  START_DATE_INVALID: 'Start date must be a valid date',
  END_DATE_INVALID: 'End date must be a valid date',
  LOCATION_MUST_BE_STRING: 'Location must be a string',
  LOCATION_NOT_EMPTY: 'Location must not be empty',
  LOCATION_LENGTH_INVALID: 'Location must be between 3 and 200 characters',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_NOT_EMPTY: 'Description must not be empty',
  CAMPAIGN_NOT_FOUND: 'Campaign not found'
}

const VOLUNTEER_MESSAGES = {
  CAMPAIGN_ID_REQUIRED: 'Campaign ID is required',
  CAMPAIGN_ID_INVALID: 'Campaign ID must be a positive integer',
  VOLUNTEER_ID_REQUIRED: 'Volunteer ID is required',
  VOLUNTEER_ID_INVALID: 'Volunteer ID must be a positive integer',
  VOLUNTEER_NAME_REQUIRED: 'Volunteer name is required',
  VOLUNTEER_NAME_MUST_BE_STRING: 'Volunteer name must be a string',
  VOLUNTEER_NAME_NOT_EMPTY: 'Volunteer name must not be empty',
  VOLUNTEER_NAME_LENGTH_INVALID: 'Volunteer name must be between 3 and 100 characters',
  STATUS_REQUIRED: 'Status is required',
  STATUS_INVALID: 'Status must be one of the following: pending, active, rejected',
  REGISTER_DATE_INVALID: 'Register date must be a valid date',
  REGISTER_DATE_REQUIRED: 'Register date is required',
  ALREADY_REGISTERED: 'Volunteer has already registered for this campaign',
  NOT_REGISTERED: 'Volunteer is not registered for this campaign',
  REGISTRATION_FAILED: 'Volunteer registration failed',
  REGISTRATION_ID_REQUIRED: 'registration ID is required',
  REGISTRATION_ID_INVALID: 'registration ID must be a positive integer'
}
module.exports = {
  USER_MESSAGES,
  COMMON,
  ROLE_MESSAGES,
  FUND_CATEGORY_MESSAGES,
  FUND_MESSAGES,
  CAMPAIGN_MESSAGES,
  VOLUNTEER_MESSAGES
}
