const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH: 'Name must be between 1 and 100 characters',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  FIRST_NAME_IS_REQUIRED: 'First name is required',
  FIRST_NAME_LENGTH: 'First name must be between 2 and 30 characters',
  LAST_NAME_IS_REQUIRED: 'Last name is required',
  LAST_NAME_LENGTH: 'Last name must be between 2 and 30 characters',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_STRONG:
    'Password must be contain at least one uppercase letter, one lowercase letter, one number, and one special character',
  PASSWORD_LENGTH: 'Password must be between 8 and 50 characters',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_MATCH: 'Confirm password must match the password',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_IS8601_INVALID: 'Date of birth must be a valid ISO 8601 date',
  LOGIN_INCORRECT: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Login successfully',
  REGISTER_SUCCESS: 'Register successfully',
  UN_AUTHORIZATION: 'Unauthorized',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  LOGOUT_SUCCESS: 'Logout successfully',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_VERIFY_SUCCESS: 'Email verify successfully',
  EMAIL_VERIFY_FAILED: 'Email verify failed',
  EMAIL_WAS_VERIFIED: 'Email was verified',
  USER_NOT_FOUND: 'User not found',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend verify email successfully',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCCESS: 'Verify forgot password token successfully',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
  BIO_IS_STRING: 'Bio must be a string',
  BIO_LENGTH: 'Bio must be between 1 and 200 characters',
  LOCATION_IS_STRING: 'Location must be a string',
  LOCATION_LENGTH: 'Location must be between 1 and 200 characters',
  WEBSITE_IS_STRING: 'Website must be a string',
  WEBSITE_LENGTH: 'Website must be between 1 and 200 characters',
  USERNAME_IS_STRING: 'Username must be a string',
  USERNAME_INVALID: 'Username must be 1 to 15 characters long and only contain letters, numbers, or underscores',
  USERNAME_EXISTS: 'Username already exists',
  AVATAR_IS_STRING: 'Avatar must be a string',
  IMAGE_URL_IS_STRING: 'Image URL must be a string',
  IMAGE_URL_LENGTH: 'Image URL must be between 1 and 400 characters',
  UPDATE_PROFILE_SUCCESS: 'Update profile successfully',
  FOLLOWER_USER_ID_IS_NOT_EMPTY: 'Follower user ID is not empty',
  FOLLOW_SUCCESS: 'Follow successfully',
  CANNOT_FOLLOW_YOURSELF: 'Cannot follow yourself',
  ALREADY_FOLLOWING: 'Already following',
  UN_FOLLOW_SUCCESS: 'Unfollow successfully',
  HAVE_NOT_FOLLOWING: 'have not following user',
  CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
  NEW_PASSWORD_IS_SAME_OLD_PASSWORD: 'New password must be different from the old password.',
  OLD_PASSWORD_IS_REQUIRED: 'Old password is required',
  OLD_PASSWORD_IS_WRONG: 'Old password is wrong',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successfully',
  FORBIDDEN: 'Forbidden',
  USER_ID_REQUIRED: 'User ID is required',
  USER_ID_INVALID: 'User ID is invalid',
  REFRESH_TOKEN_IS_STRING: 'Refresh token must be a string',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  AVATAR_IS_REQUIRED: 'Avatar is required',
}

const COMMON = {
  PAGE_INVALID: 'Page must be a positive integer',
  PAGE_SIZE_INVALID: 'Page size must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer',
  LIMIT_MAX: 'Limit must not exceed 100',
  SORT_BY_INVALID: 'Sort by must be a valid field',
  SORT_ORDER_INVALID: 'Sort order must be either "asc" or "desc"',
  MEDIA_IS_ARRAY: 'Restaurant media must be an array',
  MEDIA_ITEM_INVALID: 'Each media item must be a valid object with type and url',
  MEDIA_ITEM_TYPE_INVALID: 'Media type must be one of the following: image, video, audio',
  MEDIA_ITEM_URL_INVALID: 'Media URL must be a valid URL',
  MEDIA_ITEM_URL_LENGTH: 'Media URL must be between 1 and 400 characters',
  MEDIA_ITEM_REQUIRED: 'At least one media item is required',
  MEDIA_ITEM_MAX: 'A maximum of 10 media items is allowed',
  MEDIA_ITEM_MIN: 'At least one media item is required',
  SEARCH_MUST_BE_STRING: 'Search must be a string',
  ID_IS_INVALID: 'ID is invalid',
  ID_IS_REQUIRED: 'ID is required',
  IS_ACTIVE_MUST_BE_BOOLEAN: 'isActive must be a boolean',
  ROLE_INVALID: 'Role is invalid'
}

const ROLE_MESSAGES = {
  NAME_IS_REQUIRED: 'Role name is required',
  NAME_IS_INVALID: 'Role name must be a string',
  ROLE_IS_DUPLICATE: 'Role already exists',
  ROLE_ID_IS_REQUIRED: 'Role ID is required',
  ROLE_ID_IS_INVALID: 'Role ID is invalid'
}


module.exports = {
  USER_MESSAGES,
  COMMON,
  ROLE_MESSAGES,
}
